# Generated by Django 4.2.9 on 2024-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Verification Code'),
        ),
    ]
